working_dir : absolute/or/relative/path/to/target/git/repo/root
filter :
  branch : master
  restrict :
    commit_count : 1000  # commit_count limit or -1 to ignore limit
    # precise date or -1 to ignore date bound
    from_date : 2017-01-01
    to_date : 2018-01-01
  key_words:
    first:
      - bug
      - fix
      - check
      - issue
      - mistake
      - incorrect
      - fault
      - defect
      - error
    second:
      - integer overflow
      - integer underflow
      - memory leak
output :
  dir : absolute/or/relative/path/where/you/want/to/store/the/result
  file_name : report.db
  content :
    # comment those lines that you don't need to output
    - hash
    - summary  # needed to filter commits using key words
    - description  # needed to filter commits using key words
    - date
    - author
    - diff  # stored in output.dir/diff folder
