working_dir : ~/Code/linux
filter :
  branch : master
  restrict :
    commit_count : -1  # commit_count limit or -1 to ignore limit
    # precise date or -1 to ignore date bound
    from_date : 2018-01-01
    to_date : -1
    NOF : 50
  keywords :
    first :
      - bug
      - fix
      - check
      - issue
      - mistake
      - incorrect
      - fault
      - defect
      - error
    second :
      - memory leak
      - error path
      - unchecked return
      - error handl
      - check return
      - error check
  LOC : 20
  discard_file_names :
    - test
    - news
    - contribute
  ignore_case : True
checkout: True
